// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: internal/api/internal.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RewireRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DownstreamAddress *string                `protobuf:"bytes,1,opt,name=downstream_address,json=downstreamAddress,proto3,oneof" json:"downstream_address,omitempty"`
	UpstreamAddress   *string                `protobuf:"bytes,2,opt,name=upstream_address,json=upstreamAddress,proto3,oneof" json:"upstream_address,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RewireRequest) Reset() {
	*x = RewireRequest{}
	mi := &file_internal_api_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewireRequest) ProtoMessage() {}

func (x *RewireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewireRequest.ProtoReflect.Descriptor instead.
func (*RewireRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_internal_proto_rawDescGZIP(), []int{0}
}

func (x *RewireRequest) GetDownstreamAddress() string {
	if x != nil && x.DownstreamAddress != nil {
		return *x.DownstreamAddress
	}
	return ""
}

func (x *RewireRequest) GetUpstreamAddress() string {
	if x != nil && x.UpstreamAddress != nil {
		return *x.UpstreamAddress
	}
	return ""
}

var File_internal_api_internal_proto protoreflect.FileDescriptor

const file_internal_api_internal_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/api/internal.proto\x12\x03api\x1a\x1bgoogle/protobuf/empty.proto\"\x9f\x01\n" +
	"\rRewireRequest\x122\n" +
	"\x12downstream_address\x18\x01 \x01(\tH\x00R\x11downstreamAddress\x88\x01\x01\x12.\n" +
	"\x10upstream_address\x18\x02 \x01(\tH\x01R\x0fupstreamAddress\x88\x01\x01B\x15\n" +
	"\x13_downstream_addressB\x13\n" +
	"\x11_upstream_address2S\n" +
	"\x1bInternalMessageBoardService\x124\n" +
	"\x06Rewire\x12\x12.api.RewireRequest\x1a\x16.google.protobuf.EmptyB\"Z razpravljalnica/internal/api;apib\x06proto3"

var (
	file_internal_api_internal_proto_rawDescOnce sync.Once
	file_internal_api_internal_proto_rawDescData []byte
)

func file_internal_api_internal_proto_rawDescGZIP() []byte {
	file_internal_api_internal_proto_rawDescOnce.Do(func() {
		file_internal_api_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_internal_proto_rawDesc), len(file_internal_api_internal_proto_rawDesc)))
	})
	return file_internal_api_internal_proto_rawDescData
}

var file_internal_api_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_api_internal_proto_goTypes = []any{
	(*RewireRequest)(nil), // 0: api.RewireRequest
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_internal_api_internal_proto_depIdxs = []int32{
	0, // 0: api.InternalMessageBoardService.Rewire:input_type -> api.RewireRequest
	1, // 1: api.InternalMessageBoardService.Rewire:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_api_internal_proto_init() }
func file_internal_api_internal_proto_init() {
	if File_internal_api_internal_proto != nil {
		return
	}
	file_internal_api_internal_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_internal_proto_rawDesc), len(file_internal_api_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_internal_proto_goTypes,
		DependencyIndexes: file_internal_api_internal_proto_depIdxs,
		MessageInfos:      file_internal_api_internal_proto_msgTypes,
	}.Build()
	File_internal_api_internal_proto = out.File
	file_internal_api_internal_proto_goTypes = nil
	file_internal_api_internal_proto_depIdxs = nil
}
