// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: internal/api/internal.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WALEntry_Op int32

const (
	WALEntry_OP_SAVE   WALEntry_Op = 0
	WALEntry_OP_DELETE WALEntry_Op = 1
)

// Enum value maps for WALEntry_Op.
var (
	WALEntry_Op_name = map[int32]string{
		0: "OP_SAVE",
		1: "OP_DELETE",
	}
	WALEntry_Op_value = map[string]int32{
		"OP_SAVE":   0,
		"OP_DELETE": 1,
	}
)

func (x WALEntry_Op) Enum() *WALEntry_Op {
	p := new(WALEntry_Op)
	*p = x
	return p
}

func (x WALEntry_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WALEntry_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_api_internal_proto_enumTypes[0].Descriptor()
}

func (WALEntry_Op) Type() protoreflect.EnumType {
	return &file_internal_api_internal_proto_enumTypes[0]
}

func (x WALEntry_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WALEntry_Op.Descriptor instead.
func (WALEntry_Op) EnumDescriptor() ([]byte, []int) {
	return file_internal_api_internal_proto_rawDescGZIP(), []int{0, 0}
}

type WALEntry_Target int32

const (
	WALEntry_TARGET_USER    WALEntry_Target = 0
	WALEntry_TARGET_TOPIC   WALEntry_Target = 1
	WALEntry_TARGET_MESSAGE WALEntry_Target = 2
	WALEntry_TARGET_LIKE    WALEntry_Target = 3
)

// Enum value maps for WALEntry_Target.
var (
	WALEntry_Target_name = map[int32]string{
		0: "TARGET_USER",
		1: "TARGET_TOPIC",
		2: "TARGET_MESSAGE",
		3: "TARGET_LIKE",
	}
	WALEntry_Target_value = map[string]int32{
		"TARGET_USER":    0,
		"TARGET_TOPIC":   1,
		"TARGET_MESSAGE": 2,
		"TARGET_LIKE":    3,
	}
)

func (x WALEntry_Target) Enum() *WALEntry_Target {
	p := new(WALEntry_Target)
	*p = x
	return p
}

func (x WALEntry_Target) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WALEntry_Target) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_api_internal_proto_enumTypes[1].Descriptor()
}

func (WALEntry_Target) Type() protoreflect.EnumType {
	return &file_internal_api_internal_proto_enumTypes[1]
}

func (x WALEntry_Target) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WALEntry_Target.Descriptor instead.
func (WALEntry_Target) EnumDescriptor() ([]byte, []int) {
	return file_internal_api_internal_proto_rawDescGZIP(), []int{0, 1}
}

type WALEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Op            WALEntry_Op            `protobuf:"varint,2,opt,name=op,proto3,enum=api.WALEntry_Op" json:"op,omitempty"`
	Target        WALEntry_Target        `protobuf:"varint,3,opt,name=target,proto3,enum=api.WALEntry_Target" json:"target,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WALEntry) Reset() {
	*x = WALEntry{}
	mi := &file_internal_api_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALEntry) ProtoMessage() {}

func (x *WALEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALEntry.ProtoReflect.Descriptor instead.
func (*WALEntry) Descriptor() ([]byte, []int) {
	return file_internal_api_internal_proto_rawDescGZIP(), []int{0}
}

func (x *WALEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WALEntry) GetOp() WALEntry_Op {
	if x != nil {
		return x.Op
	}
	return WALEntry_OP_SAVE
}

func (x *WALEntry) GetTarget() WALEntry_Target {
	if x != nil {
		return x.Target
	}
	return WALEntry_TARGET_USER
}

func (x *WALEntry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApplyWALEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *WALEntry              `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyWALEntryRequest) Reset() {
	*x = ApplyWALEntryRequest{}
	mi := &file_internal_api_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyWALEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyWALEntryRequest) ProtoMessage() {}

func (x *ApplyWALEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyWALEntryRequest.ProtoReflect.Descriptor instead.
func (*ApplyWALEntryRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_internal_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyWALEntryRequest) GetEntry() *WALEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type RewireRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DownstreamId      *int64                 `protobuf:"varint,1,opt,name=downstream_id,json=downstreamId,proto3,oneof" json:"downstream_id,omitempty"`
	DownstreamAddress *string                `protobuf:"bytes,2,opt,name=downstream_address,json=downstreamAddress,proto3,oneof" json:"downstream_address,omitempty"`
	UpstreamId        *int64                 `protobuf:"varint,3,opt,name=upstream_id,json=upstreamId,proto3,oneof" json:"upstream_id,omitempty"`
	UpstreamAddress   *string                `protobuf:"bytes,4,opt,name=upstream_address,json=upstreamAddress,proto3,oneof" json:"upstream_address,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RewireRequest) Reset() {
	*x = RewireRequest{}
	mi := &file_internal_api_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewireRequest) ProtoMessage() {}

func (x *RewireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewireRequest.ProtoReflect.Descriptor instead.
func (*RewireRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_internal_proto_rawDescGZIP(), []int{2}
}

func (x *RewireRequest) GetDownstreamId() int64 {
	if x != nil && x.DownstreamId != nil {
		return *x.DownstreamId
	}
	return 0
}

func (x *RewireRequest) GetDownstreamAddress() string {
	if x != nil && x.DownstreamAddress != nil {
		return *x.DownstreamAddress
	}
	return ""
}

func (x *RewireRequest) GetUpstreamId() int64 {
	if x != nil && x.UpstreamId != nil {
		return *x.UpstreamId
	}
	return 0
}

func (x *RewireRequest) GetUpstreamAddress() string {
	if x != nil && x.UpstreamAddress != nil {
		return *x.UpstreamAddress
	}
	return ""
}

var File_internal_api_internal_proto protoreflect.FileDescriptor

const file_internal_api_internal_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/api/internal.proto\x12\x03api\x1a\x1bgoogle/protobuf/empty.proto\"\xf2\x01\n" +
	"\bWALEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\x02op\x18\x02 \x01(\x0e2\x10.api.WALEntry.OpR\x02op\x12,\n" +
	"\x06target\x18\x03 \x01(\x0e2\x14.api.WALEntry.TargetR\x06target\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\" \n" +
	"\x02Op\x12\v\n" +
	"\aOP_SAVE\x10\x00\x12\r\n" +
	"\tOP_DELETE\x10\x01\"P\n" +
	"\x06Target\x12\x0f\n" +
	"\vTARGET_USER\x10\x00\x12\x10\n" +
	"\fTARGET_TOPIC\x10\x01\x12\x12\n" +
	"\x0eTARGET_MESSAGE\x10\x02\x12\x0f\n" +
	"\vTARGET_LIKE\x10\x03\";\n" +
	"\x14ApplyWALEntryRequest\x12#\n" +
	"\x05entry\x18\x01 \x01(\v2\r.api.WALEntryR\x05entry\"\x91\x02\n" +
	"\rRewireRequest\x12(\n" +
	"\rdownstream_id\x18\x01 \x01(\x03H\x00R\fdownstreamId\x88\x01\x01\x122\n" +
	"\x12downstream_address\x18\x02 \x01(\tH\x01R\x11downstreamAddress\x88\x01\x01\x12$\n" +
	"\vupstream_id\x18\x03 \x01(\x03H\x02R\n" +
	"upstreamId\x88\x01\x01\x12.\n" +
	"\x10upstream_address\x18\x04 \x01(\tH\x03R\x0fupstreamAddress\x88\x01\x01B\x10\n" +
	"\x0e_downstream_idB\x15\n" +
	"\x13_downstream_addressB\x0e\n" +
	"\f_upstream_idB\x13\n" +
	"\x11_upstream_address2\x97\x01\n" +
	"\x1bInternalMessageBoardService\x12B\n" +
	"\rApplyWALEntry\x12\x19.api.ApplyWALEntryRequest\x1a\x16.google.protobuf.Empty\x124\n" +
	"\x06Rewire\x12\x12.api.RewireRequest\x1a\x16.google.protobuf.EmptyB\"Z razpravljalnica/internal/api;apib\x06proto3"

var (
	file_internal_api_internal_proto_rawDescOnce sync.Once
	file_internal_api_internal_proto_rawDescData []byte
)

func file_internal_api_internal_proto_rawDescGZIP() []byte {
	file_internal_api_internal_proto_rawDescOnce.Do(func() {
		file_internal_api_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_internal_proto_rawDesc), len(file_internal_api_internal_proto_rawDesc)))
	})
	return file_internal_api_internal_proto_rawDescData
}

var file_internal_api_internal_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_api_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_api_internal_proto_goTypes = []any{
	(WALEntry_Op)(0),             // 0: api.WALEntry.Op
	(WALEntry_Target)(0),         // 1: api.WALEntry.Target
	(*WALEntry)(nil),             // 2: api.WALEntry
	(*ApplyWALEntryRequest)(nil), // 3: api.ApplyWALEntryRequest
	(*RewireRequest)(nil),        // 4: api.RewireRequest
	(*emptypb.Empty)(nil),        // 5: google.protobuf.Empty
}
var file_internal_api_internal_proto_depIdxs = []int32{
	0, // 0: api.WALEntry.op:type_name -> api.WALEntry.Op
	1, // 1: api.WALEntry.target:type_name -> api.WALEntry.Target
	2, // 2: api.ApplyWALEntryRequest.entry:type_name -> api.WALEntry
	3, // 3: api.InternalMessageBoardService.ApplyWALEntry:input_type -> api.ApplyWALEntryRequest
	4, // 4: api.InternalMessageBoardService.Rewire:input_type -> api.RewireRequest
	5, // 5: api.InternalMessageBoardService.ApplyWALEntry:output_type -> google.protobuf.Empty
	5, // 6: api.InternalMessageBoardService.Rewire:output_type -> google.protobuf.Empty
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_api_internal_proto_init() }
func file_internal_api_internal_proto_init() {
	if File_internal_api_internal_proto != nil {
		return
	}
	file_internal_api_internal_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_internal_proto_rawDesc), len(file_internal_api_internal_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_internal_proto_goTypes,
		DependencyIndexes: file_internal_api_internal_proto_depIdxs,
		EnumInfos:         file_internal_api_internal_proto_enumTypes,
		MessageInfos:      file_internal_api_internal_proto_msgTypes,
	}.Build()
	File_internal_api_internal_proto = out.File
	file_internal_api_internal_proto_goTypes = nil
	file_internal_api_internal_proto_depIdxs = nil
}
