// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: internal/api/internal.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalMessageBoardService_Rewire_FullMethodName                   = "/api.InternalMessageBoardService/Rewire"
	InternalMessageBoardService_ExecuteDatabaseOperation_FullMethodName = "/api.InternalMessageBoardService/ExecuteDatabaseOperation"
	InternalMessageBoardService_TransferDatabase_FullMethodName         = "/api.InternalMessageBoardService/TransferDatabase"
)

// InternalMessageBoardServiceClient is the client API for InternalMessageBoardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalMessageBoardServiceClient interface {
	// Rewire the node's upstream and downstream nodes
	Rewire(ctx context.Context, in *RewireRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Request a database operation
	ExecuteDatabaseOperation(ctx context.Context, in *ExecuteDatabaseOperationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Transfer database
	TransferDatabase(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferDatabaseEvent], error)
}

type internalMessageBoardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalMessageBoardServiceClient(cc grpc.ClientConnInterface) InternalMessageBoardServiceClient {
	return &internalMessageBoardServiceClient{cc}
}

func (c *internalMessageBoardServiceClient) Rewire(ctx context.Context, in *RewireRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, InternalMessageBoardService_Rewire_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalMessageBoardServiceClient) ExecuteDatabaseOperation(ctx context.Context, in *ExecuteDatabaseOperationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, InternalMessageBoardService_ExecuteDatabaseOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalMessageBoardServiceClient) TransferDatabase(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferDatabaseEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InternalMessageBoardService_ServiceDesc.Streams[0], InternalMessageBoardService_TransferDatabase_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, TransferDatabaseEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InternalMessageBoardService_TransferDatabaseClient = grpc.ServerStreamingClient[TransferDatabaseEvent]

// InternalMessageBoardServiceServer is the server API for InternalMessageBoardService service.
// All implementations must embed UnimplementedInternalMessageBoardServiceServer
// for forward compatibility.
type InternalMessageBoardServiceServer interface {
	// Rewire the node's upstream and downstream nodes
	Rewire(context.Context, *RewireRequest) (*emptypb.Empty, error)
	// Request a database operation
	ExecuteDatabaseOperation(context.Context, *ExecuteDatabaseOperationRequest) (*emptypb.Empty, error)
	// Transfer database
	TransferDatabase(*emptypb.Empty, grpc.ServerStreamingServer[TransferDatabaseEvent]) error
	mustEmbedUnimplementedInternalMessageBoardServiceServer()
}

// UnimplementedInternalMessageBoardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalMessageBoardServiceServer struct{}

func (UnimplementedInternalMessageBoardServiceServer) Rewire(context.Context, *RewireRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rewire not implemented")
}
func (UnimplementedInternalMessageBoardServiceServer) ExecuteDatabaseOperation(context.Context, *ExecuteDatabaseOperationRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteDatabaseOperation not implemented")
}
func (UnimplementedInternalMessageBoardServiceServer) TransferDatabase(*emptypb.Empty, grpc.ServerStreamingServer[TransferDatabaseEvent]) error {
	return status.Errorf(codes.Unimplemented, "method TransferDatabase not implemented")
}
func (UnimplementedInternalMessageBoardServiceServer) mustEmbedUnimplementedInternalMessageBoardServiceServer() {
}
func (UnimplementedInternalMessageBoardServiceServer) testEmbeddedByValue() {}

// UnsafeInternalMessageBoardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalMessageBoardServiceServer will
// result in compilation errors.
type UnsafeInternalMessageBoardServiceServer interface {
	mustEmbedUnimplementedInternalMessageBoardServiceServer()
}

func RegisterInternalMessageBoardServiceServer(s grpc.ServiceRegistrar, srv InternalMessageBoardServiceServer) {
	// If the following call pancis, it indicates UnimplementedInternalMessageBoardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalMessageBoardService_ServiceDesc, srv)
}

func _InternalMessageBoardService_Rewire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RewireRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalMessageBoardServiceServer).Rewire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalMessageBoardService_Rewire_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalMessageBoardServiceServer).Rewire(ctx, req.(*RewireRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalMessageBoardService_ExecuteDatabaseOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteDatabaseOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalMessageBoardServiceServer).ExecuteDatabaseOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalMessageBoardService_ExecuteDatabaseOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalMessageBoardServiceServer).ExecuteDatabaseOperation(ctx, req.(*ExecuteDatabaseOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalMessageBoardService_TransferDatabase_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InternalMessageBoardServiceServer).TransferDatabase(m, &grpc.GenericServerStream[emptypb.Empty, TransferDatabaseEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InternalMessageBoardService_TransferDatabaseServer = grpc.ServerStreamingServer[TransferDatabaseEvent]

// InternalMessageBoardService_ServiceDesc is the grpc.ServiceDesc for InternalMessageBoardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalMessageBoardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.InternalMessageBoardService",
	HandlerType: (*InternalMessageBoardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Rewire",
			Handler:    _InternalMessageBoardService_Rewire_Handler,
		},
		{
			MethodName: "ExecuteDatabaseOperation",
			Handler:    _InternalMessageBoardService_ExecuteDatabaseOperation_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransferDatabase",
			Handler:       _InternalMessageBoardService_TransferDatabase_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/api/internal.proto",
}
