// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: internal/api/internal.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalMessageBoardService_GetWALEntries_FullMethodName = "/api.InternalMessageBoardService/GetWALEntries"
	InternalMessageBoardService_Rewire_FullMethodName        = "/api.InternalMessageBoardService/Rewire"
)

// InternalMessageBoardServiceClient is the client API for InternalMessageBoardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalMessageBoardServiceClient interface {
	// Returns WAL entries from specified id onwards
	GetWALEntries(ctx context.Context, in *GetWALEntriesRequest, opts ...grpc.CallOption) (*GetWALEntriesResponse, error)
	// Rewire the node's upstream and downstream nodes
	Rewire(ctx context.Context, in *RewireRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type internalMessageBoardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalMessageBoardServiceClient(cc grpc.ClientConnInterface) InternalMessageBoardServiceClient {
	return &internalMessageBoardServiceClient{cc}
}

func (c *internalMessageBoardServiceClient) GetWALEntries(ctx context.Context, in *GetWALEntriesRequest, opts ...grpc.CallOption) (*GetWALEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWALEntriesResponse)
	err := c.cc.Invoke(ctx, InternalMessageBoardService_GetWALEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalMessageBoardServiceClient) Rewire(ctx context.Context, in *RewireRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, InternalMessageBoardService_Rewire_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalMessageBoardServiceServer is the server API for InternalMessageBoardService service.
// All implementations must embed UnimplementedInternalMessageBoardServiceServer
// for forward compatibility.
type InternalMessageBoardServiceServer interface {
	// Returns WAL entries from specified id onwards
	GetWALEntries(context.Context, *GetWALEntriesRequest) (*GetWALEntriesResponse, error)
	// Rewire the node's upstream and downstream nodes
	Rewire(context.Context, *RewireRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedInternalMessageBoardServiceServer()
}

// UnimplementedInternalMessageBoardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalMessageBoardServiceServer struct{}

func (UnimplementedInternalMessageBoardServiceServer) GetWALEntries(context.Context, *GetWALEntriesRequest) (*GetWALEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWALEntries not implemented")
}
func (UnimplementedInternalMessageBoardServiceServer) Rewire(context.Context, *RewireRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rewire not implemented")
}
func (UnimplementedInternalMessageBoardServiceServer) mustEmbedUnimplementedInternalMessageBoardServiceServer() {
}
func (UnimplementedInternalMessageBoardServiceServer) testEmbeddedByValue() {}

// UnsafeInternalMessageBoardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalMessageBoardServiceServer will
// result in compilation errors.
type UnsafeInternalMessageBoardServiceServer interface {
	mustEmbedUnimplementedInternalMessageBoardServiceServer()
}

func RegisterInternalMessageBoardServiceServer(s grpc.ServiceRegistrar, srv InternalMessageBoardServiceServer) {
	// If the following call pancis, it indicates UnimplementedInternalMessageBoardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalMessageBoardService_ServiceDesc, srv)
}

func _InternalMessageBoardService_GetWALEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWALEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalMessageBoardServiceServer).GetWALEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalMessageBoardService_GetWALEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalMessageBoardServiceServer).GetWALEntries(ctx, req.(*GetWALEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalMessageBoardService_Rewire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RewireRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalMessageBoardServiceServer).Rewire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalMessageBoardService_Rewire_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalMessageBoardServiceServer).Rewire(ctx, req.(*RewireRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalMessageBoardService_ServiceDesc is the grpc.ServiceDesc for InternalMessageBoardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalMessageBoardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.InternalMessageBoardService",
	HandlerType: (*InternalMessageBoardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWALEntries",
			Handler:    _InternalMessageBoardService_GetWALEntries_Handler,
		},
		{
			MethodName: "Rewire",
			Handler:    _InternalMessageBoardService_Rewire_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/api/internal.proto",
}
